# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  android-ubuntu:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [14.x]
        
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - run: javac -version
    - run: sudo update-java-alternatives -l || echo OK
    - run: sudo update-alternatives --list javac
    - run: sudo update-java-alternatives -s $(sudo update-java-alternatives -l | grep 8 | cut -d " " -f1) || echo OK
    - name: Removing Java
      run: sudo apt-get purge openjdk* -y && sudo rm -rf /usr/lib/jvm/*
    - name: Install Java 8
      run: sudo apt install openjdk-8-jdk -y
    - run: javac -version
